#!/bin/sh
# elvis: reddit	-- Search reddit (www.reddit.com)
. surfraw || exit 1

w3_usage_hook ()
{
	cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search reddit (www.reddit.com)
EOF
	w3_global_usage
}


w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
	w3_browse_url "https://www.reddit.com"
else
	escaped_args=$(w3_url_of_arg $w3_args)
	search_url="https://www.reddit.com/search?q="

	# Map variables to parameters
	## No mappings

	# Add the search to url
	search_url="${search_url}${escaped_args}"
	w3_browse_url "$search_url"
fi